### PR TITLE
Articles form validation

### PR DESCRIPTION
**Pull request by Feven90**

### CODE REVIEW

**Comment by ripalpate** [comment]
👍 its working. Please pull down the current master before you merge the branch?

**Comment by mjleavell** [comment]
👍

**Comment by mjleavell** [comment]
@Feven90 dont merge yet. getting errors.

**Comment by mjleavell** [comment]
@Feven90 
a few things:
* ```@import './../../../styles/variables';``` needs to be added to articles.scss
* is it possible to go back to the navbar that is currently the one in master? I like the font, but the color makes the links hard to read.

**Comment by shanedwilson** [comment]
I'm seconding @mjleavell's comment. Broken here and the navbar is harder to read than the current master.

**Comment by mjleavell** [comment]
👍

**Comment by shanedwilson** [comment]
👍

**Pull request merged**
