### PR TITLE
Sdw empty locations

### LINKED ISSUE #16: Delete Weather Location
### Story
As a user, I should be able to delete a weather location.

### Acceptance Criteria
* A delete button should print to the weather div
* Clicking 'delete' should remove then the location should be removed from the database
* Clicking 'delete' should empty the weather div

revised

### PR DESCRIPTION
**Pull request by shanedwilson**
closes #16.

delete icon should appear on the weather card.

clicking it should remove the location from the dropdown and a warning to select a location should appear.

if you delete all of your locations, a warning should appear to add a location.

i'm experiencing some intermittent weirdness and can't tell if it's internet speed, bad code, firebase or a curse on my head.

report back and let me know how it's working for you.

### CODE REVIEW

**Comment by shanedwilson** [comment]
@mjleavell weird. I’m not seeing that. I’ll investigate.

**Comment by shanedwilson** [comment]
@mjleavell Give it another look-see. I've tweaked the code a hair.

**Comment by mjleavell** [comment]
looks great! 👍 💯 🎉 🦄 👍

**Comment by shanedwilson** [comment]
sorry. made one tiny change that should not affect performance, but give it another quick peak. i'm leaving this branch alone now. promise.

**Comment by mjleavell** [comment]
@shanedwilson still working great! 👍  awesome job!!

**Comment by ripalpate** [comment]
@shanedwilson. great job shane. Delete functionality is working. However,I am experiencing some weirdness. When I added zipcode and I am switching the zipcode, sometimes it displays the weather and sometimes it's keep on saying please select location for current weather. Seems like weather data is not coming back. 

I am giving you 👍

**Comment by shanedwilson** [comment]
@ripalpate there is definitely inconsistent bugginess.  hoping to sit down w/ an instructor saturday and tighten it up.

**Pull request merged**
