### PR TITLE
Fm add articles

### PR DESCRIPTION
**Pull request by Feven90**
#21 
- clicking on Add button, you should see a form to add articles and all other articles should hide. 
- The articles you added should show up in firebase

#22
- clicking on edit button should bring you a form filled with information to edit.

### CODE REVIEW

**Comment by shanedwilson** [comment]
👍

**Comment by mjleavell** [comment]
I found a few bugs:
1. When you click the read me link, the page refreshes but a new tab never opens with the article
2. If you add an article and then click the edit button, the url shows up as undefined. 

I'm go ahead and give you a thumbs up but will add a bug ticket for the read me link.
👍

**Comment by ripalpate** [comment]
👍

**Comment by mjleavell** [comment]
👍

**Pull request merged**
