### PR TITLE
Rp style

### PR DESCRIPTION
**Pull request by ripalpate**
- Added background image
- Added Navbar tabs style
- Fonts style to Chufas
- Contents are aligned according to group discussion

### CODE REVIEW

**Comment by shanedwilson** [comment]
Looks really good. My only opinion is I think I like the navbar links better as words instead of buttons, but I'll defer to y'all on that.

👍

**Comment by shanedwilson** [comment]
👍

**Comment by mjleavell** [comment]
👍 looks great!

**Comment by mjleavell** [comment]
@ripalpate when you get a chance, can you fix the merge conflicts and merge this branch? I'm trying to finalize messages. thanks!

**Pull request merged**
