### PR TITLE
Rp navbar attr

### PR DESCRIPTION
**Pull request by ripalpate**

### CODE REVIEW

**Comment by mjleavell** [comment]
whenever I click one of the navbar tabs, the login button shows up.

**Comment by ripalpate** [comment]
@mjleavell  yeah I had issue with it and I have fixed it.

**Comment by mjleavell** [comment]
@ripalpate navbar looks good. However, I think that you can just add the href tags to each a tag. I tried it out, and it worked the same with just less code.

**Comment by shanedwilson** [comment]
working here. 👍 If you refactor the code i'll recheck it.

**Comment by ripalpate** [comment]
@mjleavell  yeah, I asked you guys in slack. I have tried both ways and it works so I can change it by just adding href.

**Comment by mjleavell** [comment]
👍 looks good!

**Comment by shanedwilson** [comment]
Hold on merge. My delete functionality for weather is gone.

**Pull request merged**
