### PR TITLE
Ml edit message

### LINKED ISSUE #18: Edit Messages
### User Story
As a user, I want to have the ability to edit my messages. 

### Acceptance Criteria
**When** I click the edit button
**Then** the message should turn into a text input
**And** I can update the message
**And** clicking enter updates the message
**And** timestamp is updated and message is displayed at the bottom of the message board

### Tech Notes
* similar to edit in TODO app
* axios call to eidt message
* message should be edited in DOM and firebase
* click event on edit button
* enter event

### PR DESCRIPTION
**Pull request by mjleavell**
closes #18 

* edit message updates timestamp and adds (edited) to messages

### CODE REVIEW

**Comment by shanedwilson** [comment]
minor bug. if one edits a previously edited message, the 'small' style tag is in the edit field.

**Comment by mjleavell** [comment]
> minor bug. if one edits a previously edited message, the 'small' style tag is in the edit field.

good catch! im working on a fix

**Comment by ripalpate** [comment]
👍

**Comment by Feven90** [comment]
👍

**Comment by mjleavell** [comment]
fixed bug

**Comment by shanedwilson** [comment]
👍

**Comment by mjleavell** [comment]
merged this ticket because i got verbal confirmation from team

**Pull request merged**
