### PR TITLE
Rp timestamp

### LINKED ISSUE #52: TimeStamp for Events
## User Story
When user adds event, user need to see day and time the event entered. Also , user needs to see events' sorted by timestamp.

## Development
- Add timestamp variable and export it.
- add in JSON file
- call timestamp function in adding object function

## Acceptance Criteria
When User add events , he should be able to see timestamp when events are entered also it should organize by timestamp.

### PR DESCRIPTION
**Pull request by ripalpate**
close #52

-  Added timestamp for events
- events are sorting according to timestamp

### CODE REVIEW

**Comment by mjleavell** [comment]
@ripalpate  Sorting the events by the timestamp is off. When i added 2 events, the most recent event is in the middle, rather than at the top. 
image

**Comment by ripalpate** [comment]
@mjleavell I fixed it. Can you take a look? Thank you!:)

**Comment by shanedwilson** [comment]
👍

**Comment by mjleavell** [comment]
👍 good to merge

**Comment by shanedwilson** [comment]
Hold on merge. My delete functionality for weather is gone.

**Pull request merged**
